name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-bibtex-extra \
          biber \
          latexmk

    - name: Install Source Serif Pro
      run: |
        sudo tlmgr init-usertree
        sudo tlmgr install sourceserifpro

    - name: Compile LaTeX document
      run: |
        cd cv
        make

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: CV PDF
        path: cv/build/main.pdf

    - name: Clean up
      run: |
        cd cv
        make clean
